"""User add bot column

Revision ID: ad05edb2fa97
Revises: c03f81f5b27c
Create Date: 2024-01-25 11:48:57.481814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad05edb2fa97'
down_revision = 'c03f81f5b27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot', sa.Boolean(), default=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bot')

    # ### end Alembic commands ###
