"""User add tank column

Revision ID: c03f81f5b27c
Revises: 0f111abd6865
Create Date: 2024-01-25 10:21:41.473999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03f81f5b27c'
down_revision = '0f111abd6865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tank', sa.String(), nullable=True, default=None))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tank')

    # ### end Alembic commands ###
